<h1>My Jupyter Notebook on IBM Watson Studio</h1>

<b>Sarang Deshmukh</b>
Software Enggineer

<i>Data Science leads us to the future and I want my place in the future. That is why I am interested in DS</i>

<h3> we are Adding numbers in cell 5</h3>

In [2]:
5+10

15

<!DOCTYPE html>
<html>
<body>

<h2>Ordered List with Numbers</h2>

<ol type="1">
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>  
    
    <h2>A basic HTML table</h2>

<table style="width:100%">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
</table>
    
</body>
</html>